language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ginkooo
  password:
    secure: ssALJJXBRbmIdmx7AmICvT8O2AoRi2Uk24fhbN1+QMekewD4xDvrvhIpOeTDOnyWBPI/Af7OCIu6pSTHW1I9bCXUCQorfMHs/GXhQfSksWp+jh7yCaEJrPEySIT5eZTDVpJcJM9vrTMqaswegdbsJNz0/TfFoJP/S+/ToCR2XAEUqvHsk+8+QbMh38xlFGTSMgUKj1IbH1jpVrTH5klrjCEXCPKSTKcWpgbyQUyccabFzJ38r5rcl018m6TTuF12xo2GJ2yMFpmfBZ3Pdu4Xe1Q/9HYH4o7jBgkJpnucqQpzzJ8hemfc/PRBOwdIPRtlzU0iLJuYYqti38EyGG+ii+ysg5k50Gh0z3uVrURTVIpkoPPHpdtb1ysalAjEqQalhhvXKhWxca0WhXrY3Si+94SwJ0NwPJhHetkck1CTd6uj667NJ8cycdONe9j0S7y1Xk8oIEyzt+cDC2Z29a4anyVbBseyKBHPfkzJZryn2rTjnrlQmHXs2MKF4kkDG8CHqfCvNjhbGWcKP9wBbC1aA3RQ/SsMRTYd/155kjNGiKugqn8gWKnDpvfbp9G01sC+WHxn+uDyygG7QuN5OfzVS7YvHTZU5cwtocOiXt3tV+w0+crYgVd9HClFcO3/W2gFfStwB170XMGHVnSs3sloRzvl7udZ2LeSCPWlvgj6nU4=
  on:
    tags: true
