language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ginkooo
  password:
    secure: cGCkkCXc50aCr2Qn0k0jslzcSQCUIzj7TTasOzf7X1DIRGmTdUh6YRrSPc418KkmJgrtCdvMboDNswd+A0I8EM7QurZlA0yTsvCvh1WJ8a/eAmIygk34Q9xeS1m37rlTEhuZCZBideFlRJkPcbFHTBz+Hx0vPhn3h+/R2mxoDRqlXFha6+wccbLgi5kXZOnhx2Uqd2mZSOIbm0R1WIktgos6ea9Fmu3ykPl04jtzZx7HVx/4Sq2/QxaiRjBe73pckaBvQLjK5BLkk55JseXxZAtiITnkq7qSym4wgSUAeWjioeUleVYMPMY6hNX4ad7hjgvhWY+RWIBFAeNn2MU+6dd/ZrLCqGg17nRKI0YLaYKw7JvwO2MD0qU44gaTmALC454WCjiZ2bOp2+PrvspfX1dD6uiA637ZEWqzKnJZoUFVBwjLxVTcQR2/134RBqK2tPoZot9/iHdfLVfB4jj2wd/ZHIQ7oWJbJRLg/ePkn8SkcxvBVr/9qQw2B9fA7lVqviN47UmPqGBVZo5TqH3JNzQoUriu8oPBgVLkftKA7/BkW3o3ijdODV0+JJ3rB2B38McReI3QnsoXAs25gTbShYLR71dSfcw5xlqLhEzx6kPwiEqdZSRnCCcX4RL/9bQmK+j2Sz/tUqzMwjkd5xgJXET9cjf9ixWZzbFaUSvdEUo=
  on:
    tags: true
