language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ginkooo
  password:
    secure: 6ciop9eUdqsaflMrDd0MYF6dnMtQyVBf3nTyr4HgJQ/8zRqJE3ALvOF3JoNjnuR4UbZfCc3zrLbEOYwCsdQKiGhvkcSYBEB1fvuF8JpD3fLZbBrrhHvyVg9uxiw+GLTixNRpiAvkO27Hb/P3MR9iCQ4oZpYcLX3hEt/YWLHcX71e3Ze+uL/mMR86UmDir6WPMPSylhzIU2HX7PmKa6/raILb614IRghEtxl/i1T0ZjBYyPm7zXlNPu5DqeJf9Ldp9HecAOlAuOL8/TYRvsVnWyuPV4p36Bd4jNjIFl/LZe2mmsmg2tZ6xovieWnMD+Mt28kXrtuYnihUXqeqAbckdbfrTLuto0sVK+oxJlUYzZQLWaEXOflLpE7rE2EA6ZWfKUqFJG1kAUHJljLuEMo7YXTu5cmX9XI2yvg+4GuFk36MWyUMR4XUKBZyv/8DFugf9g7z02X9VL1SkyNPfcP8d1E/1yDtHN7SZFSLreWZXkblkgmoRxu7j/d2kQaohfDWrVnIleF00VoRfqYjfntsTcJRnKXcaHYOXh8X8tX/hSk43Ci9lWxVC5jpBY4Au4XWoHUTIHS8LozQNAoRTo8rtdMU73TBnXipgBV9f2Vg6fn3HFqr90jDBpWcZqCg9cW5P5hzaLaMRBFDwNRygOdmCsQ8ewhP3v/5fhLm5yNqZHI=
  on:
    tags: true
