language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ginkooo
  password:
    secure: ecNqBGqhfFXEVMKFddxxDnoJLr4TyJ5fOOo3E4D2BL+cHLt53MPh+GDANJJSLfdtc0RNzMbdy+OyGWaNd2U+Tk9j4hKn4T8ovXQZdHqw9I+2pU5EQQytezw5tCymDosJD/kLLqlJxaOCd6Op47kgBSMc1UDwXGzlp16vwycer0muCvDfzbGoZ9l8cc50wGOfVUhORIWNthhYnxZVJlH4qxeKZa4u7PZ9DecMAnWBDHC954XsK8Ezndm8zzysEuPfOvMRrDp0MU6qjeBMwzhTaI92rSPcmo5lnoIwYVIZFFjnqqz90JKcizYNwCVbjDVaDG8SI6yodyE0RudaSTryNBPOk0fWVLcMIcQHiT2HDjPHXADdbLGDTKT326RDENXL/DbQlPbYmea8GE4hk/W+eP7CgEdmuXKuEsZEdmZ7m0uDqF+vIb+sBlc2vAwcDGnWf9KWMJ23aH8/WTOE4DlZLLMjeDAQHp//hvPRzmmQI6VDRsC1zgoM80N5ss1K6HPX+W+aCgqxozekFIPMfa+XCjl7DfU+CD299PbaSIjqRriZHrTWQ8ZkkON4K7TZpSvqKooL1s0++Br21iK6UO8t9Fsjfs0dXvMy9IaBT9cnvFFzyInOuIcwtaM3iVBWWP9o5pVGQejyBbJobheyZ6fXg0WLlq0nLw5eYQm7t4sT6gI=
  on:
    tags: true
